version: '3.8'

services:
  ingesta-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingesta-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OCR__Endpoint=http://174.138.117.37:8081/extract-lines
    restart: unless-stopped
